### ISSUE TITLE
Exemplo

### ISSUE THREAD

**Issue by gustavobrunoro** [PauloLuan/android-dynamic-form#1]
Boa tarde..

poderia disponibilizar o executável do projeto para execução tentei adicionar ao meu projeto como modulo, mais não conseguir

**Comment by PauloLuan** [comment]
Bom dia @gustavobrunoro, eu nem lembrava que esse código existia, é de 6 anos atrás, completamente depreciado e antigo, não recomendo a sua utilização. Mas caso queira, fique a vontade para copiar, atualizar e distribuir da forma que achar mais adequado, abraços!
